#!/bin/bash

PHP=/opt/plesk/php/7.4/bin/php

function show_help {
  echo "Use pfw -d 1.1.1.1 to block 1.1.1.1"
}

# Helper Function:
# Create loopback SSH session to confirm the changes. Plesk requires this to confirm changes.
# You will be prompted to enter the root password before it can finish.
function plesk_firewall_confirm() {
  plesk bin modules/firewall/settings --confirm
  echo "============================================================"
  echo "To confirm Plesk firewall settings, must enter root password"
  echo "============================================================"
  ssh root@localhost "plesk bin modules/firewall/settings --confirm"
  if [ $? -ne 0 ]; then
    echo "Confirm failed. Probably timed out. Trying one last time..."
    plesk bin modules/firewall/settings --confirm
    ssh root@localhost "plesk bin modules/firewall/settings --confirm"
  fi
}


# A POSIX variable
OPTIND=1 # Reset in case getopts has been used previously in the shell.
# Initialize our own variables:
block_ip=""

while getopts "h?d:" opt; do
    case "$opt" in
    h|\?)
      show_help
      exit 0
      ;;
    d) block_ip=$OPTARG
       ;;
    esac
done

shift $((OPTIND-1))
[ "${1:-}" = "--" ] && shift

if [ -z "$block_ip" ]; then
    echo "You did not provide an IP address to block. Use -d IP to block an IP."
    exit 0
else
  
  if [ $(systemctl is-active fail2ban) == "active" ]; then 
  
    if [ ! -e /etc/fail2ban/jail.d/pfw.conf ]; then
      echo "First time fail2ban setup in progress..."
      echo '[pfw]
enabled = true
action = iptables-allports[name="pfw", protocol=tcp, bantime=1w]
bantime = 1w' > /etc/fail2ban/jail.d/pfw.conf
      systemctl restart fail2ban
      sleep 10 #wait for service to restart
    fi
    echo "Adding $block_ip to fail2ban jail: pfw"
    /usr/bin/fail2ban-client set pfw banip $block_ip
    
  else
    # Ref: https://support.plesk.com/hc/en-us/articles/115002552134-How-to-manage-Plesk-firewall-via-CLI- 
    
    RULE_ID=$(plesk db -Ne 'select id from module_firewall_rules where configuration_id=2 and object like "%Custom Blocks%"');
    if [ -z "$RULE_ID" ]; then
      echo "Creating new rule for Custom Blocks..."
      /usr/local/psa/bin/modules/firewall/settings -s -name 'Custom Blocks' -direction input -action deny -remote-addresses $block_ip
    else
      SERIALIZED_RULE=$(plesk db -Ne 'select object from module_firewall_rules where configuration_id=2 and object like "%Custom Blocks%"')
      EXISTING_IPS=$(echo $SERIALIZED_RULE | $PHP -R '$arr = unserialize($argn); echo implode(",",$arr["from"]);')
      echo "Adding $block_ip to $EXISTING_IPS in rule 'Custom Blocks'..."
      /usr/local/psa/bin/modules/firewall/settings -s -id $RULE_ID -remote-addresses "$block_ip,$EXISTING_IPS"
    fi
    
    /usr/local/psa/bin/modules/firewall/settings -a # apply
    plesk_firewall_confirm
  fi
fi